backend:
  name: github
  repo: Stabats/Golden-Search # Path to your GitHub repository
  branch: main # Branch to update (optional; defaults to master)
  
# This line should *not* be indented
media_folder: "assets" # Media files will be stored in the repo under images/uploads
